AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM Template for Twilio WhatsApp Webhook Lambda in Java 21 with ChatGPT integration and audio processing

Globals:
  Function:
    Timeout: 300  # Increase timeout to allow for transcription job polling
    MemorySize: 512

Resources:
  TwilioWebhookFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.adlanda.TwilioWebhookLambda::handleRequest
      Runtime: java21
      CodeUri: TwilioWebhookLambda
      Environment:
        Variables:
          OPENAI_SECRET_ID: "OpenAiApiKey"
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Sid: "AllowSecretsManagerAccess"
              Effect: "Allow"
              Action:
                - "secretsmanager:GetSecretValue"
              Resource: "*"   # Ideally, restrict to your secret's ARN
            - Sid: "AllowS3AccessForAudioMessages"
              Effect: "Allow"
              Action:
                - "s3:PutObject"
                - "s3:GetObject"
              Resource: "arn:aws:s3:::twilio-audio-messages-eu-west-1-andreslandaaws/*"
            - Sid: "AllowTranscribeAccess"
              Effect: "Allow"
              Action:
                - "transcribe:StartTranscriptionJob"
                - "transcribe:GetTranscriptionJob"
              Resource: "*"  # Ideally, restrict further if possible
      Events:
        TwilioWebhookEvent:
          Type: Api
          Properties:
            Path: /webhook
            Method: post

Outputs:
  TwilioWebhookApi:
    Description: "API Gateway endpoint URL for the Twilio Webhook"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/webhook"
